## Câu 1

In [ ]:
# Numpy code
import numpy as np

# Đặt seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
np.random.seed(2024)

# Tạo 2 mảng với các giá trị số nguyên ngẫu nhiên trong
# khoảng [-10, 10) với kích thước (3, 4)
arr_1 = np.random.randint(-10, 10, (3, 4))
arr_2 = np.random.randint(-10, 10, (3, 4))

# Chuyển vị array
# Cách 1: Sử dụng hàm np.transpose()
arr2_transposed = np.transpose(arr_2)
# # Cách 2: Sử dụng toán tử T
# arr2_transposed = arr_2.T

# Nhân ma trận
result_matmul = np.matmul(arr_1, arr2_transposed)
# In ra màn hình
print("array 1:\n", arr_1)
print("array 2:\n", arr_2)
print("array 2 sau khi chuyển vị:\n", arr2_transposed)
print("Kết quả phép nhân arr_1 với  arr_2:\n", result_matmul )


array 1:
 [[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
array 2:
 [[ 5  0  4  5]
 [ 1 -3  8 -1]
 [-4  0 -9 -5]]
array 2 sau khi chuyển vị:
 [[ 5  1 -4]
 [ 0 -3  0]
 [ 4  8 -9]
 [ 5 -1 -5]]
Kết quả phép nhân arr_1 với  arr_2:
 [[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]


In [ ]:
# Pytorch code
import torch
# Thiết lập seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
torch.manual_seed(2024)

# Tạo 2 tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_1 = torch.randint(-10, 10, size=(3, 4))
tensor_2 = torch.randint(-10, 10, size=(3, 4))

# Chuyển vị tensor
# Cách 1: Sử dụng phương thức torch.t()
#tensor2_transposed = torch.t(tensor_2)
# Cách 2: Sử dụng phương thức torch.transpose()
# Cách 3: sử dụng toán tử chuyển vị T
tensor2_transposed = tensor_2.T

# Nhân ma trận
result_matmul = torch.matmul(tensor_1, tensor2_transposed)

# In ra màn hình
print("tensor 2:\n", tensor_1)
print("tensor 2:\n", tensor_2)
print("tensor 2 sau khi chuyển vị:\n", tensor2_transposed)
print("Kết quả phép nhân tensor_1 với  tensor_2:\n", result_matmul )


tensor 2:
 tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
tensor 2:
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
tensor 2 sau khi chuyển vị:
 tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])
Kết quả phép nhân tensor_1 với  tensor_2:
 tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])


In [ ]:
# TensorFlow code
import tensorflow as tf
# Thiết lập seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
tf.random.set_seed(2024)

# Tạo 2 tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_1 = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.dtypes.int32)
tensor_2 = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.dtypes.int32)
# Chuyển vị tensor
tensor2_transposed = tf.transpose(tensor_1)

# Nhân ma trận
result_matmul = tf.matmul(tensor_1, tensor2_transposed)

# In ra màn hình
print("tensor 1:\n", tensor_1)
print("tensor 2:\n", tensor_2)
print("tensor 2 sau khi chuyển vị:\n", tensor2_transposed)
print("Kết quả phép nhân tensor_1 với  tensor_2:", result_matmul)

tensor 1:
 tf.Tensor(
[[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]], shape=(3, 4), dtype=int32)
tensor 2:
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
tensor 2 sau khi chuyển vị:
 tf.Tensor(
[[-6  4  7]
 [-2  4  1]
 [ 0 -9  2]
 [-2  3 -5]], shape=(4, 3), dtype=int32)
Kết quả phép nhân tensor_1 với  tensor_2: tf.Tensor(
[[ 44 -38 -34]
 [-38 122  -1]
 [-34  -1  79]], shape=(3, 3), dtype=int32)


## Câu 2

In [ ]:
# Đặt seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
np.random.seed(2024)

# Tạo mảng với các giá trị số nguyên ngẫu nhiên trong
# khoảng [-10, 10) với kích thước (3, 3)
arr = np.random.randint(-10, 10, (3, 3))

# Tính tổng của tất cả các phần tử trong mảng
total_sum = np.sum(arr)

# Tính tổng theo cột (theo chiều dọc)
column_sum = np.sum(arr, axis=0)

# Tính tổng theo hàng (theo chiều ngang)
row_sum = np.sum(arr, axis=1)

# In ra màn hình
print("Mảng:\n", arr)
print("Tổng của tất cả các phần tử trong mảng:\n", total_sum)
print("Tổng theo cột:\n", column_sum)
print("Tổng theo hàng:\n", row_sum)


Mảng:
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Tổng của tất cả các phần tử trong mảng:
 -53
Tổng theo cột:
 [-15 -11 -27]
Tổng theo hàng:
 [-22 -16 -15]


In [ ]:
# Pytorch code
import torch
# Thiết lập seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
torch.manual_seed(2024)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_1 = torch.randint(-10, 10, size=(3, 3))
# Tính tổng tensor
tensor_sum = torch.sum(tensor_1)
# Tính tổng tensor theo cột axis = 0
tensor_sum_axis_0 = torch.sum(tensor_1, axis=0)
# Tính tổng tensor theo hàng axis = 1
tensor_sum_axis_1 = torch.sum(tensor_1, axis=1)

# In ra màn hình
print("tensor:\n", tensor_1)
print("Tổng các phần tử trong tensor:\n", tensor_sum)
print("Tổng theo cột:\n", tensor_sum_axis_0)
print("Tổng theo hàng:\n", tensor_sum_axis_1)

tensor:
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tổng các phần tử trong tensor:
 tensor(-27)
Tổng theo cột:
 tensor([ -8,  -6, -13])
Tổng theo hàng:
 tensor([ -4, -27,   4])


In [ ]:
# TensorFlow code
import tensorflow as tf
# Thiết lập seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
tf.random.set_seed(2024)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_1 = tf.random.uniform((3, 3), minval=-10, maxval=10, dtype=tf.dtypes.int32)
# Tính tổng tensor
tensor_sum = tf.reduce_sum(tensor_1)
# Tính tổng tensor theo cột axis = 0
tensor_sum_axis_0 = tf.reduce_sum(tensor_1, axis=0)
# Tính tổng tensor theo hàng axis = 1
tensor_sum_axis_1 = tf.reduce_sum(tensor_1, axis=1)

# In ra màn hình
print("tensor:\n", tensor_1)
print("Tổng các phần tử trong tensor:\n", tensor_sum)
print("Tổng theo cột:\n", tensor_sum_axis_0)
print("Tổng theo hàng:\n", tensor_sum_axis_1)

tensor:
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tổng các phần tử trong tensor:
 tf.Tensor(-1, shape=(), dtype=int32)
Tổng theo cột:
 tf.Tensor([-17   5  11], shape=(3,), dtype=int32)
Tổng theo hàng:
 tf.Tensor([-8  6  1], shape=(3,), dtype=int32)
