# Bài 1

In [3]:
import numpy as np
import torch as t
import tensorflow as tf

nparange = np.arange(10)
print(nparange)
torchrange = t.arange(10)
print(torchrange)
tfrange = tf.range(10)
print(tfrange)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


# Bài 2

In [4]:
npeye = np.eye(3,dtype = int)
print(npeye)
torcheye = t.eye(3, dtype = int)
print(torcheye)
tfeye = tf.eye(3, dtype = tf.int32)
print(tfeye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]], shape=(3, 3), dtype=int32)


# Bài 3

In [5]:
np.random.seed(2024)
np_randmat = np.random.rand(3,4)
np_randmat2 = np.random.randint(-10, 11, (3,4))
print(np_randmat)
print(np_randmat2)

t.manual_seed(2024)
t_randmat = t.rand(3,4)
t_randmat2 = t.randint(-10, 11, (3,4))
print(t_randmat)
print(t_randmat2)

tf.random.set_seed(2024)
tf_randmat = tf.random.uniform([3,4])
tf_randmat2 = tf.random.uniform([3,4], -10, 11, dtype = tf.int32)
print(tf_randmat)
print(tf_randmat2)

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
[[ 5  1 -3  8]
 [-1 -4 10  0]
 [-9 -5  9 -6]]
tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
tensor([[-10,   3,  -4,  10],
        [  2,   7,  -1,   9],
        [  1,   3, -10,   3]])
tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 7  6  2  8]
 [ 0 -1 -4  6]
 [-2  5 10 -3]], shape=(3, 4), dtype=int32)
