In [3]:
import numpy as np 
import tensorflow as tf 
import torch

In [4]:
list_1D = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr_1D = np.array(list_1D)
print(arr_1D)

[1 2 3 4 5 6 7 8 9]


In [6]:
tensor_1D_pt = torch.tensor(list_1D)
(tensor_1D_pt)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
tensor_1D_tf = tf.convert_to_tensor(list_1D)
print(tensor_1D_tf)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [8]:
list_2D = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]

arr_2D = np.array(list_2D)
print(arr_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(arr_2D.shape)

(3, 3)


In [10]:
print(arr_2D.dtype)

int64


In [11]:
print(type(arr_2D))

<class 'numpy.ndarray'>


In [12]:
tensor_2D_pt = torch.tensor(arr_2D)
print(tensor_2D_pt)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [13]:
print(tensor_2D_pt.shape)

torch.Size([3, 3])


In [14]:
print(tensor_2D_pt.dtype)

torch.int64


In [15]:
print(type(tensor_2D_pt))

<class 'torch.Tensor'>


In [16]:
print(tensor_2D_pt.device)

cpu


In [17]:
tensor_2D_tf = tf.convert_to_tensor(list_2D)
print(tensor_2D_tf)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [18]:
print(tensor_2D_tf.dtype)

<dtype: 'int32'>


In [19]:
print(tensor_2D_tf.device)

/job:localhost/replica:0/task:0/device:CPU:0


In [20]:
print(type(tensor_2D_tf))

<class 'tensorflow.python.framework.ops.EagerTensor'>
